apiVersion: v1
kind: Secret
metadata:
  name: user-management-secret
type: Opaque
stringData:
  spring.datasource.username: app
  spring.datasource.password: apppass
  app.jwt.secret: ReplaceWithStrongJWTSecretBase64OrPlain
  admin.username: admin
  admin.email: admin@example.com
  admin.password: changeme
